
service: strika-api
app: strika-app
org: juanesarango

frameworkVersion: '2'
useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  configValidationMode: error
  apiGateway:
    shouldStartNameWithService: true

functions:
  whoami:
    handler: handler.whoami
    events:
      - http:
          path: whoami
          method: get
  api:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

