
service: strika-api
app: strika-api
org: juanesarango

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

functions:
  whoami:
    handler: handler.whoami
    events:
      - http:
          path: whoami
          method: get
